#' List reports found in report directory
#'
#' A list of raw report files in `report_dir`.
#' This function descends the directory rooted at `report_dir` to find all reports to be run.
#' Reports to be run are identified by filename extensions,
#' by default `c(".Rmd", ".Rnw")`.
#'
#' @param report_dir A string that identifies a directory of reports to be generated.
#' @param report_suffixes A vector of strings of report suffixes. Default is `c(".Rmd", ".Rnw")`.
#'
#' @return A vector of absolute paths to reports to be generated.
#'
#' @export
#'
#' @examples
reports_to_generate <- function(report_dir, report_suffixes = c(".Rmd", ".Rnw")) {
  all_files <- list.files(path = report_dir, full.names = TRUE, recursive = TRUE, include.dirs = TRUE)
  reports_to_run <- list()
  for (suff in report_suffixes) {
    reports_to_run <- append(files_to_run, endsWith(all_files, suffix = suff))
  }
  reports_to_run
}


#' Generate reports found in report directory
#'
#' This function descends the directory rooted at `report_dir` and executes `knitr::knit` on all
#' files with `report_suffixes`.
#'
#' Each report name is suffixed by date and time.
#' Previous reports are shuffled to a folder named `<<report_name>>_prev`.
#'
#' @param report_file A vector of absolute paths to reports that need to be run, .
#'                    probably generated by `reports_to_generate()`.
#' @param report_output_folder A string that identifies the directory into which the completed reports should be written.
#'                             Default is `drake::readd(SEAPSUTWorkflow::target_names[["report_output_folder"]]`
#'
#' @return
#' @export
#'
#' @examples
generate_reports <- function(report_files,
                             report_output_folder = drake::readd(SEAPSUTWorkflow::target_names[["report_output_folder"]])) {
}
