#' List reports found in report directory
#'
#' Makes a list of raw report files in `report_dirs`.
#' This function descends the directories rooted at `report_dirs` to find all reports to be run.
#' Reports to be run are identified by filename extensions,
#' by default `c(".Rmd", ".Rnw")`.
#'
#' Users can override the default value of `report_dirs` to supply their own
#' report directory(ies).
#' If users want to also include the default reports,
#' be sure to include `system.file(file.path("reports"), package = "SEAPSUTWorkflow")`
#' in the vector of paths supplied to `report_dirs`.
#'
#' @param report_dirs A string that identifies a directory of reports to be generated.
#'                    Default is `system.file(file.path("reports"), package = "SEAPSUTWorkflow")`,
#'                    which provides some default reports.
#' @param report_suffixes A vector of strings of report suffixes. Default is `c(".Rmd", ".Rnw")`.
#'
#' @return A vector of absolute paths to reports to be generated.
#'
#' @export
#'
#' @examples
reports_paths <- function(report_dirs = system.file(file.path("reports"), package = "SEAPSUTWorkflow"),
                          report_suffixes = c(".Rmd", ".Rnw")) {

  # Make a list in which we'll collect paths to all reports that need to be run.
  reports_to_run <- list()
  # Cycle through all paths
  for (rd in report_dirs) {
    all_files <- list.files(path = rd, full.names = TRUE, recursive = TRUE, include.dirs = TRUE)
    for (suff in report_suffixes) {
      which_files_are_reports <- which(endsWith(all_files, suffix = suff), arr.ind = TRUE)
      if (length(which_files_are_reports) > 0) {
        reports_to_run <- append(reports_to_run, all_files[[which_files_are_reports]])
      }
    }
  }
  unlist(reports_to_run)
}


#' Generate reports found in report directory
#'
#' This function descends the directory rooted at `report_dir` and executes `knitr::knit()` on all
#' files with `report_suffixes`.
#'
#' Each report name is suffixed by date and time.
#' Previous reports are shuffled to a folder named `<<report_name>>_prev`.
#'
#' @param report_files A vector of absolute paths to reports that need to be run,
#'                     probably generated by `reports_paths()`.
#' @param report_output_folder A string that identifies the directory into which the completed reports should be written.
#'                             Default is `drake::readd(SEAPSUTWorkflow::target_names[["report_output_folder"]]`
#'
#' @return
#' @export
#'
#' @examples
generate_reports <- function(report_files,
                             report_output_folder = drake::readd(SEAPSUTWorkflow::target_names[["report_output_folder"]])) {
}
